In [1]:
import numpy as np

## Numpy array operation 

### 1.Basic Operation

In [11]:
arr=np.arange(1,11)
print(f"Basic slicing : {arr[1:4]}") #(x:y) , x=for row , y= for columns
print(f"With step : {arr[1:9:2]}")  #(x:y:z), x,y = for indexing , z=for step jump
print(f"Negative indexing : {arr[-3:-1]}") # for reverse indexing , index starts for -1 and not 0

Basic slicing : [2 3 4]
With step : [2 4 6 8]
Negative indexing : [8 9]


### 2.Printing specific elements

In [14]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(f"Specific element : {arr[1,1]}" )
print(f"Entire row : {arr[2]}")
print(f"Entire column: {arr[:,1]}")

Specific element : 5
Entire row : [7 8 9]
Entire column: [2 5 8]


### 3.Sorting by rows and columns

In [11]:
uns_1d=np.array([7,6,10,3,4,1,9,5,8,2])
s=np.sort(uns_1d)
print(f"Sorted array : {s}")
uns_2d=np.array([[9,1],[1,2],[3,1]])
print(f"Sorted array in 2D for columns :\n {np.sort(uns_2d , axis =0)}")
print(f"Sorted array in 2D for rows :\n {np.sort(uns_2d , axis=1)}")

Sorted array : [ 1  2  3  4  5  6  7  8  9 10]
Sorted array in 2D for columns :
 [[1 1]
 [3 1]
 [9 2]]
Sorted array in 2D for rows :
 [[1 9]
 [1 2]
 [1 3]]


### 4.Filter and Filter with mask


In [ ]:
n=np.arange(1,11)

e=n[n%2==0]
print(f"Filter : {e}")

mask=n>5
print(f"Filtering with mask as numbers greater than 5: {n[mask]}")


Filter : [ 2  4  6  8 10]
Filtering with mask as numbers greater than 5: [ 6  7  8  9 10]


### 5.Fancy indexing vs np.where()

In [ ]:
n=np.arange(1,11)

indices=[0,2,4]
print(n[indices])

r=np.where(n>5)
print(n[r])

ca=np.where(n>5 , n*2 , n)
print(ca)

[1 3 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
