## 1.Numpy and arrays

In [1]:
import numpy as np
import time

## 2.Creating array from list

In [3]:
arr1=np.array([1,2,3,4,5])
print(arr1)

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## 3.Numpy array vs python list

In [3]:
py_list=[1,2,3,4,5,6]
print(f"List Multiplication : {py_list*2}")

np_array=np.array([1,2,3,4,5,6])
print(f"Numpy_array Multiplication : {np_array*2}")


start=time.time()
py_list=[i*2 for i in range(100000000)]
print(f"Time for list multiplication: {time.time()-start}")


start=time.time()
np_arr=np.arange(100000000)*2
print(f"Time for numpy array multiplication: {time.time()-start}")


List Multiplication : [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
Numpy_array Multiplication : [ 2  4  6  8 10 12]
Time for list multiplication: 4.464373826980591
Time for numpy array multiplication: 0.4867212772369385


## 3.Creating array from scratch

In [10]:
z=np.zeros((3,4))
print(f"Zero matrix: \n{z}")

o=np.ones((3,3))
print(f"Ones Matrix:\n{o}")

f=np.full((2,3),9)
print(f"Constant value matrix:\n{f}")

random=np.random.random((2,3))
print(f"Random value matrix:\n{random}")


seq=np.arange(0,11,2)
print(f"Sequential matrix:\n{seq}")







Zero matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant value matrix:
[[9 9 9]
 [9 9 9]]
Random value matrix:
[[0.99294292 0.34505496 0.39183223]
 [0.16161173 0.04776669 0.10069638]]
Sequential matrix:
[ 0  2  4  6  8 10]


## Vector , Matrix and Tensor 

In [15]:
v=np.array([1,2,3,4,5])
print(f"Vector Array: {v}")

m=np.array([[1,2,3],[4,5,6]])
print(f"Matrix Array:\n {m}")

t=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(f"Tensor: \n {t}")


Vector Array: [1 2 3 4 5]
Matrix Array:
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


## Array Properties

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(f"Shape: {arr.shape}")
print(f"Dimension : {arr.ndim}")
print(f"Size: {arr.size}")


Shape: (2, 3)
Dimension : 2
Size: 6
