## Numpy saving and loading functions

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

### 1.Saving Numpy as npy

In [12]:
np.save("Array1.npy",array1)
np.save("Array2.npy",array2)
np.save("Array3.npy",array3)

### Loading npy back as numpy array 

In [13]:
load1=np.load("Array1.npy")
print(load1)
load2=np.load("Array2.npy")
print(load2)

[[1 2 3]
 [4 5 6]]
[[0.578713   0.89720372 0.11927867]
 [0.09254175 0.19201203 0.22098378]
 [0.08308737 0.64791106 0.58027336]]


## Image color invert